### ISSUE TITLE
Bad message in new installation when listing marks.

### ISSUE THREAD

**Issue by tregusti** [kevinsjoberg/m#4]
A new installation gives this result when trying to list all bookmarks.

```
❯ m -l                                                                                                                                                                                                    
cat: /Users/glenn/.marks: No such file or directory
```

A better message would be nice.

**Comment by kevinsjoberg** [comment]
@tregusti better late than never. 🙂 I've rewritten `m` completely. It's now bash only and the aforementioned bug have been solved.
